spring:
  application:
    name: PrimeiroJobSpringBatch
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch_old?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialec
  batch:
    initialize-schema: always
